# Developed by Fedir Sinchuk
# mail: fedir.sinchuk@outlook.com
AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  VpcIdParameter:
    Type: AWS::EC2::VPC::Id
    Description: Select your VPC
  SubnetIdParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Allowed list of subnets
  SSHKeyParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select your SSH key for EC2 instance
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Select one of available size of your EC2 instance
Resources:
  Ec2Instance: 
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-8a3f9ae8
      SecurityGroups:
        - !Ref ADVITSecurityGroup
      IamInstanceProfile: !Ref ADVITInstanceProfile
      Tags:
        -
          Key: Name
          Value: IDV-IT EC2 old version
        -
          Key: Region
          Value: !Join
            - ""
            - - "EC2 region: "
              - !Ref AWS::Region
 
  ADVITSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        -
          Key: Name
<<<<<<< Updated upstream
          Value: Security group 1111 for ADV-IT test task
  ADVITLeastPrevilegeRole:
=======
          Value: Security group for ADV-IT test task
  ADVITLeastPrevilegeRole: 
>>>>>>> Stashed changes
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - ec2.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
  ADVITRolePolicies: 
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: ADVITRolePolicies
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - 
            Effect: Deny
            Action: '*'
            Resource: '*'
      Roles: 
        - 
          Ref: ADVITLeastPrevilegeRole
  ADVITInstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
<<<<<<< Updated upstream
      Path: "/"
      Roles: ["ADVITLeastPrevilegeRole"]
      Tags:
        -
          Key: Name
          Value: ADVIT Instance profile for ADVITLeastPrevilegeRole which do nothing
    
  
=======
      Path: /
      Roles: 
        - 
          Ref: ADVITLeastPrevilegeRole  
>>>>>>> Stashed changes
