Parameters:
    VpcIdParameter:
      Type: AWS::EC2::VPC::Id
      Description: Select your VPC
    SSHKeyParameter:
       Type: AWS::EC2::KeyPair::KeyName
       Description: Select your SSH key for EC2 instance
    InstanceTypeParameter:
      Description: "EC2 instance type"
      Type: String
      Default: t2.micro
      AllowedValues:
        - t2.micro
        - m1.small
        - m1.large
    SubnetsParameters:
      Type: List<AWS::EC2::Subnet::Id>
      Description: Allowed list of subnets

Mappings: 
    RegionMap: 
      ap-southeast-2: 
        HVM64: "ami-8a3f9ae8"
      us-west-1: 
        HVM64: "ami-0bdb828fd58c52235"

Resources:
    # Ec2Instance: 
    #   Type: AWS::EC2::Instance
    #   Properties:
    #     InstanceType: !Ref InstanceTypeParameter
    #     ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ]
    #     SubnetId: !Select [ 0, !Ref SubnetsParameters ]   
    #     SecurityGroupIds:
    #       - !Ref ADVITSecurityGroup
    #   # IamInstanceProfile: !Ref ADVITInstanceProfile
    #     #  NetworkInterfaces:
    #     #   - NetworkInterfaceId: !Ref 'Eth0'
    #     #     DeviceIndex: '0'
    #     Tags:
    #       -
    #         Key: Name
    #         Value: IDV-IT EC2 Last
    #       -
    #         Key: Region
    #         Value: !Join
    #           - ""
    #           - - "EC2 region: "
    #             - !Ref AWS::Region
    #----------------------------------------------------------------
    ADVITSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:   
        VpcId: !Ref VpcIdParameter
        GroupDescription: Enable SSH via port 22
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        Tags:
          -
            Key: Name
            Value: Security group for ADV-IT test task    
    #--------------------------------------------------------------
    ADVITLaunchTemplate:
        Type: AWS::EC2::LaunchTemplate
        Properties: 
          LaunchTemplateName: !Sub ${AWS::StackName}-launch-template
          LaunchTemplateData: 
            # BlockDeviceMappings: 
            #   - Ebs:
            #       VolumeSize: 8
            #     DeviceName: /dev/sdf
            CreditSpecification: 
              CpuCredits: Unlimited
            ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ]
            InstanceType: !Ref InstanceTypeParameter
            KeyName: !Ref SSHKeyParameter
            Monitoring: 
              Enabled: true
            SecurityGroupIds: 
              - !Ref ADVITSecurityGroup

    #---------------------------------------------------------------
    ADVITLoadBalancer:
      Type: AWS::ElasticLoadBalancing::LoadBalancer
      Properties:
        Subnets: !Ref 'SubnetsParameters'
        CrossZone: 'true'
        Listeners:
        - LoadBalancerPort: '80'
          InstancePort: '80'
          Protocol: HTTP
        HealthCheck:
          Target: HTTP:80/
          HealthyThreshold: '3'
          UnhealthyThreshold: '5'
          Interval: '30'
          Timeout: '5'
        ConnectionDrainingPolicy:
          Enabled: 'true'
          Timeout: '300'
        Tags:
          -
            Key: Name
            Value: ADV-IT load balancer  

    #---------------------------------------------------------------
    AutoScalingGroup:
      Type: AWS::AutoScaling::AutoScalingGroup
      Properties:
        AvailabilityZones: !GetAZs ''
        LoadBalancerNames: [!Ref 'ADVITLoadBalancer']
        Cooldown: 120
        #InstanceId: !Ref Ec2Instance
        DesiredCapacity: 1
        MaxSize: 1
        MinSize: 1
        Tags:
          -
            Key: Name
            Value: ADV-IT auto re-run instance
            PropagateAtLaunch: 'true'
        VPCZoneIdentifier: !Ref 'SubnetsParameters'
        LaunchTemplate:
          LaunchTemplateId: !Ref ADVITLaunchTemplate
          Version: !GetAtt ADVITLaunchTemplate.LatestVersionNumber

    #-------------------------------- Done
    # LaunchConfig: 
    #   Type: AWS::AutoScaling::LaunchConfiguration
    #   Properties: 
    #     KeyName: 
    #       Ref: SSHKeyParameter
    #     #InstanceId: !Ref Ec2Instance
    #     InstanceType: !Ref InstanceTypeParameter
    #     ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region", HVM64 ]
    #     SecurityGroups: [ !Ref ADVITSecurityGroup ]
       

# Outputs: 
#     AutoscalingGroup: 
#       Description: "The newly created asg"
#       Value: 
#         Ref: "AutoScalingGroup"
#     LaunchConfig:
#       Description: "the newly created launch config"
#       Value: 
#         Ref: "LaunchConfig"
        
# AWSTemplateFormatVersion: "2010-09-09"