Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:  ami-8a3f9ae8
      SecurityGroups:
        - !Ref MySecGroup
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "EC2 at region"
              - !Ref AWS::Region
  MySecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH via port 22
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0