Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-8a3f9ae8
      Tags:
        - Key: "Name"
          Value: !Join [" ",[Second,EC2,With,SecurityGroup]]
      SecurityGroups:
        - !Ref MySecGroup
  MySecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0